// Public surface of @agent-custody/receipts. Framework adapters live on subpaths, ./sdk/<framework>, because they import optional peers.
export { AUTHORIZATION_PREDICATE_TYPE, buildAuthorizationStatement } from "./receipt.ts";
export type { AuthorizationBundle, AuthorizationPredicate, AuthorizationStatement } from "./receipt.ts";
export type { GatewayOptions } from "./gateway.ts";
export { buildRequest, restUpstream } from "./rest.ts";
export { openExporter, otlpExporter, spanFor } from "./otel.ts";
export { fileBackend, importLogFile, PostgresLog, PostgresTenancy, RateLimiter } from "./log-store.ts";
export type { AppendResult, LogBackend, PostgresLike, PostgresLogOptions, RateLimitOptions, Tenant, TokenRecord } from "./log-store.ts";
export type { OtelConfig, OtlpOptions, ReceiptExporter } from "./otel.ts";
export type { IssuerOptions } from "./issue.ts";
export type { RestOptions, UpstreamClient } from "./rest.ts";
export * from "./config.ts";
export * from "./crypto.ts";
export * from "./delegation.ts";
export * from "./gateway.ts";
export * from "./issue.ts";
export * from "./log.ts";
export * from "./log-sink.ts";
export * from "./policy.ts";
export * from "./receipt.ts";
export * from "./verify.ts";
export * from "./sdk/index.ts";
export * from "./sidecar.ts";
export * from "./upstream.ts";
export * from "./retention.ts";
